#!/usr/bin/env bash

#color codes
RED='\033[1;31m'
YELLOW='\033[1;33m'
BLUE="\\033[38;5;27m"
SEA="\\033[38;5;49m"
GREEN='\033[1;32m'
CYAN='\033[1;36m'
NC='\033[0m'

#emoji codes
CHECK_MARK="${GREEN}\xE2\x9C\x94${NC}"
X_MARK="${RED}\xE2\x9C\x96${NC}"
PIN="${RED}\xF0\x9F\x93\x8C${NC}"
CLOCK="${GREEN}\xE2\x8C\x9B${NC}"
ARROW="${SEA}\xE2\x96\xB6${NC}"
BOOK="${RED}\xF0\x9F\x93\x8B${NC}"
HOT="${ORANGE}\xF0\x9F\x94\xA5${NC}"
WARNING="${RED}\xF0\x9F\x9A\xA8${NC}"
RIGHT_ANGLE="${GREEN}\xE2\x88\x9F${NC}"

pushd $DOTFILES > /dev/null 2>&1
#Convert STOW_FOLDERS to array
IFS=',' read -r -a STOW_FOLDERS <<< "$STOW_FOLDERS"

for folder in "${STOW_FOLDERS[@]}"; do
    echo "  ${RIGHT_ANGLE}${GREEN} EXECUTE: ${YELLOW}stow $folder -t $HOME${NC}"
    stow -D $folder
    stow $folder -t $HOME

    if $folder == "bash"; then
        # Check if a line is in .bashrc
        if ! grep -q "if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi" "$HOME/.bashrc"; then
            echo -e "Adding source of .bash_profile to .bashrc"
            echo "if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi" >> "$HOME/.bashrc"
        fi
    fi
done
popd > /dev/null 2>&1

