#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS=(
        "nvim"
        "uwuntu"
        "bash"
    )
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES="$HOME/.dotfiles"
fi

$DOTFILES/ubuntu.dependencies

# Convert STOW_FOLDERS to comma separated string
STOW_FOLDERS=$(IFS=, ; echo "${STOW_FOLDERS[*]}")

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install



