---
- name: Detect if process is running as Administrator
  shell: |
    $User = [Security.Principal.WindowsIdentity]::GetCurrent()
    (New-Object Security.Principal.WindowsPrincipal $user).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
  register: windows_running_as_admin
  any_errors_fatal: true
  args:
    executable: powershell.exe
  
- name: Setting fact windows_running_as_admin
  set_fact:
    windows_running_as_admin = windows_running_as_admin.stdout

