---
- name: Detect if process is running as Administrator
  shell: |
    $User = [Security.Principal.WindowsIdentity]::GetCurrent()
    If (-Not(New-Object Security.Principal.WindowsPrincipal $user).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)) {
        $Ansible.Failed = True
    }
  register: windows_running_as_admin
  any_errors_fatal: true
  changed_when: false
  args:
    executable: powershell.exe
  
- name: Setting fact windows_running_as_admin
  set_fact:
    windows_running_as_admin = windows_running_as_admin.stdout

