#!/usr/bin/env bash
alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias python="python3"
alias yolo="git push origin master --force --no-verify"
alias dotFileInstall="$DOTFILES/install"
alias pjson="python -mjson.tool"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"

alias update='sudo nala update && sudo nala upgrade -y && sudo nala autoremove -y'
alias t=terraform
alias gs='git status'
alias ga='git add'
alias ll='ls -halF'
alias bt='bpytop'
alias vi='nvim'
alias vim='nvim'
alias ni='nvim'
alias g='git'
alias c='clear'
alias d='docker'
alias k='kubectl'
alias kx='kubectl exec -it'








