---
- name: Install Winget Package Manager
  shell: |
    $hasPackageManager = Get-AppPackage -name "Microsoft.DesktopAppInstaller"

    if (-Not($hasPackageManager)) {
      $releases_url = "https://api.github.com/repos/microsoft/winget-cli/releases/latest"

      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      $releases = Invoke-RestMethod -uri "$($releases_url)"
      $latestRelease = $releases.assets | Where { $_.browser_download_url.EndsWith("msixbundle") } | Select -First 1

      Add-AppxPackage -Path $latestRelease.browser_download_url
    } else {
      $false
    }
  register: install_winget_result
  changed_when: install_winget_result.stdout != 'False'
  args:
    executable: powershell.exe
