---
- name: Install game-related packages from winget
  shell: |
    $OriginallyNotInstalled = [bool](winget list {{ item }})[-1].Contains('No installed package found matching input criteria.')
    If ($OriginallyNotInstalled) {
      winget install {{ item }}
      $IsNotInstalled = [bool](winget list {{ item }})[-1].Contains('No installed package found matching input criteria.')
      If ($IsNotInstalled) {
        Write-Error "{{ item }} failed to install."
      }
    } else {
      $false
    }
  args:
    executable: powershell.exe
  register: winget_install_result
  changed_when: winget_install_result.stdout != 'False'
  loop:
    - Valve.Steam
    - EpicGames.EpicGamesLauncher
