---
- name: Install miscellaneous winget packages
  shell: |
    $OriginallyNotInstalled = [bool](winget list {{ item }}).Contains('No installed package')
    If ($OriginallyNotInstalled) {
      winget install {{ item }}
      $IsNotInstalled = [bool](winget list {{ item }}).Contains('No installed package')
      If ($IsNotInstalled) {
        $Ansible.Failed = $true
      }
    } else {
      $false
    }
  args:
    executable: powershell.exe
  register: winget_install_result
  changed_when: winget_install_result.stdout != 'False'
  loop:
    - Discord.Discord
    - Logitech.GHUB
    - Microsoft.Powershell
    - Microsoft.PowerToys
    - Microsoft.VisualStudioCode
    - Microsoft.Terminal
    - Notion.Notion
    - AntoineAflalo.SoundSwitch
    - Spotify.Spotify
    - Streamlabs.StreamlabsOBS
